### ISSUE TITLE
Support mopidy

### ISSUE THREAD

**Issue by GijsTimmers** [ambientsound/pms#113]
I'm using pms v0.42 on Ubuntu 17.10.

pms works nicely with mpd, but doesn't with mopidy. The main problem is that tracks don't show up in the library.

It would be nice if pms supported mopidy.

**Comment by ambientsound** [comment]
Hi @GijsTimmers.

Mopidy support is definitely a feature I'd like to implement some time soon, but version 0.42 is unsupported and there is not going to be any further development on that branch. Maybe you'd like to try the current git master instead and see how it works?

**Comment by GijsTimmers** [comment]
Hi @ambientsound, thanks for your quick response. I will try that out first.

**Comment by ambientsound** [comment]
Hi again,
Did you have any luck using master with Mopidy?

**Comment by GijsTimmers** [comment]
Hello Kim,

Haven't tried it in the meantime tbh. Still interested though.

2018-06-11 11:40 GMT+02:00 Kim Tore Jensen <notifications@github.com>:

**Comment by dvdmuckle** [comment]
Can confirm that `master` of `pms` does not work with Mopidy right now, and will instead spit out:
```
Practical Music Search 86649eb
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x858f0f]

goroutine 100 [running]:
github.com/ambientsound/pms/index.(*Index).IndexFull(0x0, 0xf27338, 0x0, 0x0, 0xc00022e000, 0x0, 0x0)
	/home/dvdmuckle/Go/src/github.com/ambientsound/pms/index/index.go:175 +0xdf
github.com/ambientsound/pms/songlist.(*Library).ReIndex.func1(0xc0001723f0)
	/home/dvdmuckle/Go/src/github.com/ambientsound/pms/songlist/library.go:109 +0x8d
created by github.com/ambientsound/pms/songlist.(*Library).ReIndex
	/home/dvdmuckle/Go/src/github.com/ambientsound/pms/songlist/library.go:107 +0x92
```
However, and this is interesting, if I start `pms` with a running instance of `mpd`, kill the `mpd` instance, then start Mopidy, `pms` is at least able to list the songs currently in the queue, even if the songs are from a remote source like Spotify.

**Comment by dvdmuckle** [comment]
Well, I was able to get it so I can switch tracks in the current queue, which was added from another client.

**Comment by ambientsound** [comment]
This error might signify that PMS was not able to pull a full copy of the song library from MPD. This makes sense since this information might not be available from Mopidy.
Because PMS' search is based on having this information stored locally, a bigger refactor will be needed in order to fully support searching through Mopidy.

**Comment by dvdmuckle** [comment]
That sounds about right, especially considering if other music backends like Spotify are enabled, which present a very large library to look through.
